/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.35.0
  Forc version: 0.35.3
  Fuel-Core version: 0.17.3
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;

interface TokenContractAbiInterface extends Interface {
  functions: {
    mint_to_address: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'mint_to_address', values: [BigNumberish, AddressInput, BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'mint_to_address', data: BytesLike): DecodedValue;
}

export class TokenContractAbi extends Contract {
  interface: TokenContractAbiInterface;
  functions: {
    mint_to_address: InvokeFunction<[amount: BigNumberish, address: AddressInput, amount2: BigNumberish], void>;
  };
}
